### ISSUE TITLE
Sorting is broken on accounts list

### ISSUE THREAD

**Issue by sharedStake-dev** [prysmaticlabs/prysm-web-ui#150]
On this page: http://localhost:7500/dashboard/wallet/accounts

The sorting on the table is broken. 
If a user clicks on any of the headers, it doesn't actually sort by that property. 
Arrows show up hinting at an asc/desc sort but that does not actually happen.

**Comment by JHGrove3** [comment]
I made a similar comment over on the DAppNode Prysm page. But I was able to figure out more detail about it.  I'll copy my bug report.
https://github.com/dappnode/DAppNodePackage-prysm/issues/22

Describe the bug
This bug is on the page "Your Validator Accounts List"
http://prysm.dappnode/dashboard/wallet/accounts

The page features a table showing all the validators, with columns for Account Name, Validating Public Key, Validator Index, ETH Balance, Eth Effective Balance, Activation Epoch, Exit Epoch, Status, and Actions.

Upon coming to the page, the table of validators appears to be unsorted. There appears to be a loose sort where the validators with lower index numbers are higher in the list, but they are not all sorted correctly.

Each column header on the page (with the exception of Validating Public Key and Actions) has a rollover feature. When you roll over the title, an arrow appears, implying that you can sort the table by that column. The arrows point up or down. As you click them they swap up vs down sorts.

You can click the arrows and it sorts the validators that are on screen. This defaults to 5 validators every time you come to the page, but you can change the default number. Note that it only sorts the 5 that are already on the page. If there are more validators not shown, they are not included in the sort.

If you have more than 5 validators, then you need to change the "Items per page" dropdown to show them.

But when you change the Items per Page dropdown, the sort feature stops working. Even if you change it back to 5, the sort feature still will not work. The only way to restore the sort feature is to reload the page.

To Reproduce

Open Prysm with an instance that has more than 5 validators running
Go to the Account List page
Try sorting the columns, and see that it works for the 5 validators that are shown.
Change the "Items per Page" to a higher number, like 10
The table updates to show up to 10 validators
Try sorting the table. The table will no longer sort.
Change "Items per Page" back to 5
Try sorting the table. The table STILL will not sort
Reload the page, either with the Refresh button (which may require re-logging in) or by going to the home page, then returning to the Account List page.
Try sorting the table. The sort will once again work for the 5 validators shown

**Comment by rauljordan** [comment]
Fixed by @olehyev138

**Comment by JHGrove3** [comment]
Has this fix been added to the latest Prysm version? I just updated DAppNode Prysm Pyrmont to version 0.1.16 (v1.3.4 upstream) and the sorting is still not working if you view more than 5 items.

**Comment by prestonvanloon** [comment]
@JHGrove3, The web UI update is blocked by this issue: https://github.com/prysmaticlabs/prysm/issues/8664

Prysm's UI will be updated upon closure of that issue. Follow 8664 for updates. Thanks!

**Comment by james-prysm** [comment]
someone mentioned it was still not working will investigate

**Comment by james-prysm** [comment]
tested seems to be working

**Comment by james-prysm** [comment]
seems like I was wrong the sorting breaks when you change the amount of keys shown on the page.
