### ISSUE TITLE
Issues accessing Web UI from remote browser

### ISSUE THREAD

**Issue by nooz** [prysmaticlabs/prysm-web-ui#71]
**Description**
1. port 4242 forwarded to localhost (192.168.1.32)
2. --web flag added to prysmvalidator.service
3. web-host: 192.168.1.32 added to yaml config for validator service

loading http://192.168.1.32:4242 on my remote browser on another machine is successful, however the validator service exits with the following:

`time="2020-10-12 11:37:13" level=info msg="gRPC server listening on address" address="127.0.0.1:7000" prefix=rpc
time="2020-10-12 11:37:13" level=info msg="Starting Prysm web UI" address="127.0.0.1:4242" prefix=prysm-web
time="2020-10-12 11:37:13" level=info msg="Starting gRPC gateway" address="127.0.0.1:7500" prefix=gateway
time="2020-10-12 11:37:13" level=warning msg="You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=validator
time="2020-10-12 11:37:14" level=error msg="**Could not open Prysm web UI in browser" error="exit status 3" prefix=prysm-web**
`

The Web UI also displayed an error message after clicking import wallet "No response, perhaps beacon node or validator client are not running"

**Your Environment**
RPi 8GB
Pi OS 64bit

**Comment by yorickdowne** [comment]
I have the --web interface prompting me for password after installing w3m and xdg-utils in the validator docker, however the web interface then complains "no response, perhaps the beacon node or validator client are not running".

It tries to connect to localhost:7500 from the web browser, which will fail, since I am remote to the server

**Comment by rauljordan** [comment]
Resolved by https://github.com/prysmaticlabs/prysm/pull/7569, which will be available in our beta.0 release this week

**Comment by canbal99** [comment]
still have the same localhost:7500 connection problem with beta.0
<img width="1473" alt="Screen Shot 2020-10-21 at 23 18 18" src="https://user-images.githubusercontent.com/18560351/96788484-e0893080-13f3-11eb-8703-6bc8b5b58cd2.png">
